### ISSUE TITLE
Number of neighbors change the aspect origin

### ISSUE THREAD

**Issue by G-Guillard** [mrahnis/rio-terrain#9]
When invoking `rio aspect` with option `--neighbors=8`, the computed aspect is rotated 90° with regards to the output with default neighbors value (or `--neighbors=4`), whatever the `--pcs` choice.

I don’t have time to do the maths today, but I guess the issue lies in the `_ring_gradient()` function.

**Comment by mrahnis** [comment]
Thank you for this. I checked the sign and return order of the gradient components for these calculations to make everything consistent with numpy.gradient. The outputs for each combination of options should be correct now.

**Comment by G-Guillard** [comment]
Seems fixed indeed, thank you very much for your reactivity.
